language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mysql -e 'create database cascade_test_on_travis;'
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script: phpunit

